services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: todo-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/todo_db
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - postgres
      - redis
    networks:
      - todo-network

  postgres:
    image: postgres:alpine
    container_name: todo-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todo-network

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: todo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - todo-network

volumes:
  postgres_data:
  redis_data:

networks:
  todo-network:
    driver: bridge